### ISSUE TITLE
kmdr does not explain redirects

### ISSUE THREAD

**Issue by ediardo** [ediardo/kmdr.sh#5]
```
kmdr explain
💡 Enter your command: cat file.txt > /dev/null
  cat
    Concatenate files and print on the standard output
  file.txt
    An argument


🤖 Is this helpful? (Use arrow keys)
❯ Skip & Exit 
  ──────────────
  Yes 
  No 
```

**Comment by divakaran** [comment]
👍

Sent from my iPhone

On Jul 28, 2019, at 11:16 AM, Eddie Ramirez <notifications@github.com<mailto:notifications@github.com>> wrote:


kmdr explain
💡 Enter your command: cat file.txt > /dev/null  cat
    Concatenate files and print on the standard output
  file.txt
    An argument


🤖 Is this helpful? (Use arrow keys)
❯ Skip & Exit
  ──────────────
  Yes
  No
